import React from "react";

export const metadata = {
  title: "Analytic Page",
  description: "Generated by Analytic page",
};
function page() {
  return (
    <div>
      <div className="h1 text-2xl">Analytics page</div>
      <p className="mt-10">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
        aliquam totam fugit nemo molestiae dolorum ducimus. Molestias non nobis
        aut ratione error enim at. Doloribus reprehenderit asperiores impedit
        facere dicta.
      </p>
    </div>
  );
}

export default page;
