import Button from "@/app/components/Button";
import React from "react";
export const metadata = {
  title: "Settings Page",
  description: "Generated by Settings page",
};
function Settings() {
  return (
    <div>
      <div className="h1 text-2xl">Settings page</div>
      <p className="mt-10">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
        aliquam totam fugit nemo molestiae dolorum ducimus. Molestias non nobis
        aut ratione error enim at. Doloribus reprehenderit asperiores impedit
        facere dicta.
      </p>

      <Button>Go To Anaylet Page</Button>
    </div>
  );
}

export default Settings;
