import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="Head">
      <h1 className="text-2xl">Home Page</h1>
      <div className="mt-10">
        This is home page
      </div>
   </div>
  );
}
